name: Python Auto Version Tag
description: Automatically generate new tags when version file changes
author: Sam Morgan
branding:
  icon: tag
  color: blue
inputs:
  path:
    description: Path to version file
    required: true
outputs:
  version:
    description: The version defined in the version file
runs:
  using: docker
  image: Dockerfile
